### ISSUE TITLE
Enable Sheets API 

### ISSUE THREAD

**Issue by Awinspired** [Jaycar-Electronics/Motherload-Datalogger#2]
Hi There
I am new to Github so please forgive me if this is not the correct way to raise an issue or make a request. I am also new to Google Cloud Platform so this may not be an issue for other users building this project. 
I had issues with the testing of the function failing and was able to decipher the output text enough to see that Google Sheets API was not enabled in my cloud platform. 
It may be of some help to absolute amateurs like myself to mention the Sheets API will need to be enabled.
Thanks 
Mal

**Comment by Jaycar-Electronics** [comment]
You're absolutely right. sometimes it's tricky to backstep through "what was done"

I've updated the readme here: https://github.com/Jaycar-Electronics/Motherload-Datalogger/commit/d611e7b29deb18d8cf72f46760e1f573c35b9049

Thanks!
